### ISSUE TITLE
底层的设备接入

### ISSUE THREAD

**Issue by liaoyinyu** [mixlinker/fidis#1]
你好，我想具体了解一下如果我要使用这个框架，底层的设备采用哪种协议接入这个系统

**Comment by liaoyinyu** [comment]
底层设备是不是一定要接入到mixIOT系统，才可以和FIDIS对接，作数据展示和交互

**Comment by qinguoqing** [comment]
是的，FIDIS是应用层，设备相关数据的来源就是MixIOT系统，所有底层设备需要先接入到MixIOT系统。
